name: double_words_app
description: A new Flutter project that generates randoms two words and favorites them.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  material_design_icons_flutter: ^5.0.0
  cupertino_icons: ^1.0.0
  english_words: ^4.0.0
  provider: ^6.0.0
  firebase_core: ^2.15.0
  flutter_dotenv: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: MaterialIcons
      fonts:
        - asset: fonts/MaterialIcons-Regular.ttf
    - family: CupertinoIcons
      fonts:
        - asset: fonts/CupertinoIcons.ttf